#!/usr/bin/env bash
#MISE description='Install packages'

source utils.sh

OS=$(detect_os)

PACKAGES=(
  jq
  age
  osv-scanner
)

case "$OS" in
  ubuntu|debian)
    echo "Installing on $OS..."
    
    # Remove osv-scanner from packages list for manual installation
    PACKAGES=("${PACKAGES[@]/osv-scanner}")
    
    # osv-scanner https://github.com/google/osv-scanner/releases
    if ! command_exists osv-scanner; then
      echo "osv-scanner: installing manually..."
      curl -L https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64 -o osv-scanner_linux_amd64
      curl -L https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_SHA256SUMS -o osv-scanner_SHA256SUMS
      sha256sum -c osv-scanner_SHA256SUMS --ignore-missing || { echo "Checksum verification failed!"; rm osv-scanner_linux_amd64 osv-scanner_SHA256SUMS; exit 1; }
      chmod +x osv-scanner_linux_amd64
      sudo mv osv-scanner_linux_amd64 /usr/local/bin/osv-scanner
      rm osv-scanner_SHA256SUMS
    else
      echo "osv-scanner: is already installed."
    fi
    ;;

  macos)
    echo "Installing on macos..."
    ;;

  *)
    echo "Installing on $OS..."
    exit 1
    ;;
esac

install_packages "${PACKAGES[@]}"