#!/usr/bin/env bash
#MISE description='Install packages'

# ist of packages to install
PACKAGES=(
  jq
  code
  age
)

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo "Detected Debian-based Linux. Installing packages with apt..."

  # vscode https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
  sudo apt update
  sudo apt install apt-transport-https gpg wget
  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
  sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
  echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
  rm packages.microsoft.gpg
  
  sudo apt update
  for package in "${PACKAGES[@]}"; do
    echo "Installing $package..."
    sudo apt install -y "$package" || echo "$package installation failed or is already installed."
  done
elif [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Detected macOS. Installing packages with Homebrew..."
  
  for package in "${PACKAGES[@]}"; do
    echo "Installing $package..."
    brew install "$package" || echo "$package is already installed or failed."
  done
else
  echo "Unsupported OS: $OSTYPE"
  exit 1
fi